keywords: Jin,Yi-love,JIN博客,博客,Yi-love博客,前端,Jin前端,Jin前端博客
description: Jin/Yi-love/cray的个人博客

url: https://yi-love.github.io
root: /
permalink: /articles/:title
username: Jin

new_post_name: :year-:month-:day-:title.md
